<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.ean.insights.dao.mapper.InsightsResourceMapperTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2016-04-20T12:49:01" hostname="LONC02R41JVG8WL.sea.corp.expecn.com" time="0.016">
  <properties/>
  <testcase name="Map on InsightsResource with groups with database connection successful" classname="com.ean.insights.dao.mapper.InsightsResourceMapperTest" time="0.014"/>
  <testcase name="Map on InsightsResource withut groups with database connection successful" classname="com.ean.insights.dao.mapper.InsightsResourceMapperTest" time="0.0"/>
  <testcase name="Map on InsightsReportService with database connection throws exception" classname="com.ean.insights.dao.mapper.InsightsResourceMapperTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
